### ISSUE TITLE
API is breaking with Season 9 release

### ISSUE THREAD

**Issue by johnsturgeon** [johnsturgeon/apex-legends-api#81]
```
Traceback (most recent call last):
  File "/Users/johnsturgeon/Code/apex-legends-api/tests/test_player.py", line 275, in <module>
    player: ALPlayer = api.get_player(name='Xzanth', platform=ALPlatform(value='PC'))
  File "/Users/johnsturgeon/Code/apex-legends-api/apex_legends_api/al_api.py", line 98, in get_player
    return ALPlayer(basic_player_stats_data=basic_player_stats[0], events=events)
  File "/Users/johnsturgeon/Code/apex-legends-api/apex_legends_api/al_domain.py", line 314, in __init__
    self.all_legends.append(Legend(legend_name=legend_name, legend_dict=legend_dict))
  File "/Users/johnsturgeon/Code/apex-legends-api/apex_legends_api/al_domain.py", line 280, in __init__
    self.data_trackers.append(DataTracker(data_tracker))
  File "/Users/johnsturgeon/Code/apex-legends-api/apex_legends_api/al_domain.py", line 252, in __init__
    self.tracker_rank = DataTracker.TrackerRank(tracker_rank_dict=rank_dict)
  File "/Users/johnsturgeon/Code/apex-legends-api/apex_legends_api/al_domain.py", line 224, in __init__
    self.percent: float = float(tracker_rank_dict.get('topPercent'))
ValueError: could not convert string to float: 'NOT_CALCULATED_YET'
```

**Comment by johnsturgeon** [comment]
Problem is that Tracker Rank is not handling strings well.
